version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    command: [
      "redis-server", 
      "--appendonly", "yes", 
      "--maxmemory", "350mb", 
      "--maxmemory-policy", "allkeys-lru",
       "--databases", "4"
    ]
    networks:
      - redis-network
    volumes:
      - redis-data:/data
    deploy:
      resources:
        limits:
          memory: 400M
    mem_limit: 400m  
  redis-monitor:
    image: redis:latest
    container_name: redis-monitor
    entrypoint: sh -c "redis-cli -h redis MONITOR > /logs/redis-monitor.log"
    depends_on:
      - redis
    networks:
      - redis-network
    volumes:
      - ./logs:/logs
    stdin_open: true
    tty: true
  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    ports:
      - "5540:5540"
    networks:
      - redis-network
    depends_on:
      - redis

volumes:
  redis-data:
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=100m

networks:
  redis-network:
    external: true